apiVersion: v1
metadata:
  name: myapp-service
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - name: name-of-the-port
      port: 80
      targetPort: 8080
      nodePort: 30004
