apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: demo-voting-app
spec:
  containers:
    - name: voiting-app
      image: dockersamples/examlevotingapp_vote
      ports:
        - containerPort: 80
